// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/qrest/models"
)

// GroupInsertOKCode is the HTTP code returned for type GroupInsertOK
const GroupInsertOKCode int = 200

/*GroupInsertOK The group was successfully inserted.

swagger:response groupInsertOK
*/
type GroupInsertOK struct {
}

// NewGroupInsertOK creates GroupInsertOK with default headers values
func NewGroupInsertOK() *GroupInsertOK {

	return &GroupInsertOK{}
}

// WriteResponse to the client
func (o *GroupInsertOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*GroupInsertDefault Unexpected error.

swagger:response groupInsertDefault
*/
type GroupInsertDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGroupInsertDefault creates GroupInsertDefault with default headers values
func NewGroupInsertDefault(code int) *GroupInsertDefault {
	if code <= 0 {
		code = 500
	}

	return &GroupInsertDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the group insert default response
func (o *GroupInsertDefault) WithStatusCode(code int) *GroupInsertDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the group insert default response
func (o *GroupInsertDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the group insert default response
func (o *GroupInsertDefault) WithPayload(payload *models.Error) *GroupInsertDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the group insert default response
func (o *GroupInsertDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GroupInsertDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
