// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/qrest/models"
)

// GroupMembersReadOKCode is the HTTP code returned for type GroupMembersReadOK
const GroupMembersReadOKCode int = 200

/*GroupMembersReadOK The mapping of quota-group names its members.

swagger:response groupMembersReadOK
*/
type GroupMembersReadOK struct {

	/*
	  In: Body
	*/
	Payload map[string]models.GroupMembers `json:"body,omitempty"`
}

// NewGroupMembersReadOK creates GroupMembersReadOK with default headers values
func NewGroupMembersReadOK() *GroupMembersReadOK {

	return &GroupMembersReadOK{}
}

// WithPayload adds the payload to the group members read o k response
func (o *GroupMembersReadOK) WithPayload(payload map[string]models.GroupMembers) *GroupMembersReadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the group members read o k response
func (o *GroupMembersReadOK) SetPayload(payload map[string]models.GroupMembers) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GroupMembersReadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string]models.GroupMembers, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GroupMembersReadDefault Unexpected error.

swagger:response groupMembersReadDefault
*/
type GroupMembersReadDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGroupMembersReadDefault creates GroupMembersReadDefault with default headers values
func NewGroupMembersReadDefault(code int) *GroupMembersReadDefault {
	if code <= 0 {
		code = 500
	}

	return &GroupMembersReadDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the group members read default response
func (o *GroupMembersReadDefault) WithStatusCode(code int) *GroupMembersReadDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the group members read default response
func (o *GroupMembersReadDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the group members read default response
func (o *GroupMembersReadDefault) WithPayload(payload *models.Error) *GroupMembersReadDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the group members read default response
func (o *GroupMembersReadDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GroupMembersReadDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
