// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/qrest/models"
)

// GroupDeleteOKCode is the HTTP code returned for type GroupDeleteOK
const GroupDeleteOKCode int = 200

/*GroupDeleteOK The group was successfully deleted.

swagger:response groupDeleteOK
*/
type GroupDeleteOK struct {
}

// NewGroupDeleteOK creates GroupDeleteOK with default headers values
func NewGroupDeleteOK() *GroupDeleteOK {

	return &GroupDeleteOK{}
}

// WriteResponse to the client
func (o *GroupDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*GroupDeleteDefault Unexpected error.

swagger:response groupDeleteDefault
*/
type GroupDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGroupDeleteDefault creates GroupDeleteDefault with default headers values
func NewGroupDeleteDefault(code int) *GroupDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &GroupDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the group delete default response
func (o *GroupDeleteDefault) WithStatusCode(code int) *GroupDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the group delete default response
func (o *GroupDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the group delete default response
func (o *GroupDeleteDefault) WithPayload(payload *models.Error) *GroupDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the group delete default response
func (o *GroupDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GroupDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
