swagger: "2.0"

basePath: "/api/v0"

host: "localhost"

info:
  description: "" # TODO
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
  title: "" # TODO
  version: "0.0.1"

tags:
  - description: "" # TODO
    name: "api"
  - description: "Endpoints required by the system that are not public facing."
    name: "system"

schemes:
  - "http"

paths:
  /alive:
    get:
      summary: "Used by Caddy or other reverse proxy to determine if the service is alive."
      description: "Any non-200 response means the service is not alive."
      operationId: "alive"
      responses:
        200:
          description: "Service is alive."
      tags:
        - "system"

  /group:
    delete:
      consumes:
        - "application/json"
      summary: "Delete a quota-group."
      description: "" # TODO
      operationId: "groupDelete"
      parameters:
        - description: "The names of the quota-groups to delete."
          in: "body"
          name: "group"
          required: true
          schema:
            type: "array"
            items:
              type: "string"
      responses:
        200:
          description: "The group was successfully deleted."
        default:
          description: "Unexpected error."
          schema:
            $ref: "#/definitions/Error"
      tags:
        - "api"
    post:
      consumes:
        - "application/json"
      summary: "Insert a quota-group."
      description: "" # TODO
      operationId: "groupInsert"
      parameters:
        - description: "The names of the quota-groups to insert. Order matters. If a quota-group is referenced as a
        member before it was inserted, an error will occur."
          in: "body"
          name: "group"
          required: true
          schema:
            type: "array"
            items:
              $ref: "#/definitions/QuotaGroup"
      responses:
        200:
          description: "The group was successfully inserted."
        default:
          description: "Unexpected error."
          schema:
            $ref: "#/definitions/Error"
      tags:
        - "api"

  /group/members:
    delete:
      consumes:
        - "application/json"
      summary: "Delete members from the quota-group."
      description: "" # TODO
      operationId: "groupMembersDelete"
      parameters:
        - description: "The mapping of quota-group names to the snaps and member quota-groups to remove."
          in: "body"
          name: "groupMembers"
          schema:
            additionalProperties:
              $ref: "#/definitions/GroupMembers"
      responses:
        200:
          description: "The members of the group were successfully deleted."
        default:
          description: "Unexpected error."
          schema:
            $ref: "#/definitions/Error"
      tags:
        - "api"
    post:
      consumes:
        - "application/json"
      summary: "Add members to the quota-group."
      description: "" # TODO
      operationId: "groupMembersAdd"
      parameters:
        - description: "The mapping of quota-group names to the snaps and member quota-groups to add."
          in: "body"
          name: "groupMembers"
          schema:
            additionalProperties:
              $ref: "#/definitions/GroupMembers"
      responses:
        200:
          description: "The members of the group were successfully added."
        default:
          description: "Unexpected error."
          schema:
            $ref: "#/definitions/Error"
      tags:
        - "api"

  /group/limits:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      summary: "Get the resource limits for the given quota-group."
      description: "" # TODO.
      operationId: "groupLimitRead"
      parameters:
        - description: "The name of the quota-groups to get the limits for."
          in: "body"
          name: "group"
          required: true
          schema:
            type: "array"
            items:
              type: "string"
      responses:
        200:
          description: "The map of quota-group names to resource limits."
          schema:
            type: "object"
            additionalProperties:
              $ref: "#/definitions/Limits"
        default:
          description: "Unexpected error."
          schema:
            $ref: "#/definitions/Error"
      tags:
        - "api"
    post:
      consumes:
        - "application/json"
      summary: "Set the resource limits for the given quota-groups."
      description: "" # TODO
      operationId: "groupLimitWrite"
      parameters:
        - description: "The mapping of quota-group names to resource limits."
          in: "body"
          name: "groupLimitsMap"
          required: true
          schema:
            additionalProperties:
              $ref: "#/definitions/Limits"
      responses:
        200:
          description: "The resource limits were successfully set for the quota-group."
        default:
          description: "Unexpected error."
          schema:
            $ref: "#/definitions/Error"
      tags:
        - "api"

#  /group/{group}/usage: TODO
#    get:

definitions:

  # Schema for error response body.
  Error:
    properties:
      code:
        type: "integer"
        x-nullable: false
      message:
        type: "string"
        x-nullable: false
    required:
      - "code"
      - "message"
    type: "object"

  # Schema for a quota-group's members' names.
  GroupMembers:
    properties:
      snaps:
        type: "array"
        items:
          type: "string"
      subGroups:
        type: "array"
        items:
          type: "string"
    type: "object"

  # Schema for resource limits.
  Limits:
    properties:
      maxMemory:
        type: "integer"

  # Schema for quota-group.
  QuotaGroup:
    properties:
      limits:
        $ref: "#/definitions/Limits"
      name:
        type: "string"
      snaps:
        type: "array"
        items:
          type: "string"
      subGroups:
        type: "array"
        items:
          type: "string"
