// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GroupMembersDeleteHandlerFunc turns a function with the right signature into a group members delete handler
type GroupMembersDeleteHandlerFunc func(GroupMembersDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GroupMembersDeleteHandlerFunc) Handle(params GroupMembersDeleteParams) middleware.Responder {
	return fn(params)
}

// GroupMembersDeleteHandler interface for that can handle valid group members delete params
type GroupMembersDeleteHandler interface {
	Handle(GroupMembersDeleteParams) middleware.Responder
}

// NewGroupMembersDelete creates a new http.Handler for the group members delete operation
func NewGroupMembersDelete(ctx *middleware.Context, handler GroupMembersDeleteHandler) *GroupMembersDelete {
	return &GroupMembersDelete{Context: ctx, Handler: handler}
}

/* GroupMembersDelete swagger:route DELETE /group/{group}/members groupMembersDelete

Delete members from the quota-group.

*/
type GroupMembersDelete struct {
	Context *middleware.Context
	Handler GroupMembersDeleteHandler
}

func (o *GroupMembersDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGroupMembersDeleteParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GroupMembersDeleteBody group members delete body
//
// swagger:model GroupMembersDeleteBody
type GroupMembersDeleteBody struct {

	// snaps
	Snaps []string `json:"snaps"`

	// sub groups
	SubGroups []string `json:"subGroups"`
}

// Validate validates this group members delete body
func (o *GroupMembersDeleteBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this group members delete body based on context it is used
func (o *GroupMembersDeleteBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GroupMembersDeleteBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GroupMembersDeleteBody) UnmarshalBinary(b []byte) error {
	var res GroupMembersDeleteBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
