// Code generated by go-swagger; DO NOT EDIT.

// Package restapi swagger
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/v0
//  Version: 0.0.1
//  License: MIT https://opensource.org/licenses/MIT
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
