// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AliveOKCode is the HTTP code returned for type AliveOK
const AliveOKCode int = 200

/*AliveOK Service is alive.

swagger:response aliveOK
*/
type AliveOK struct {
}

// NewAliveOK creates AliveOK with default headers values
func NewAliveOK() *AliveOK {

	return &AliveOK{}
}

// WriteResponse to the client
func (o *AliveOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
